- hosts: localhost
  tasks:
  - name: Create Key pair in AWS
    ec2_key:
      name: my_keypair
      key_material: "{{ lookup('file', '/home/ec2-user/environment/testkey.pub') }}"
  - name: example ec2 group
    ec2_group:
      name: websg
      description: an example EC2 group
      vpc_id: vpc-0b8dd4d703b6228b8
      region: us-east-2
      rules:
        - proto: tcp
          from_port: 80   
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
  - ec2:
      region: us-east-2
      key_name: my_keypair
      instance_type: t2.micro
      image: ami-07c8bc5c1ce9598c3
      wait: yes
      group: websg
      count: 2
      vpc_subnet_id: subnet-0779523ee657911a1
      assign_public_ip: yes